baseURL = '/'    #https://sandyfit.github.io/Data-Portfolio/
title = 'Sandra Ramos'
theme = 'Terminal'
paginate = 2

[params]
    contentTypeName = "posts"
    themeColor = "red"
    showMenuItems = 4
    showLanguageSelector = true
    fullWidthTheme = false
    centerTheme = true
    showLastUpdated = false


[languages]
  [languages.en]
    baseURL = 'https://example.com'
    contentDir = 'content/english'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    title = "In English"
    owner = ""
    keywords = "Data Analytics, Data Science, data visualization, Machine Learning, Python, SQL, Portfolio"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Sandra Ramos"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "https://cv-data-analytics.vercel.app/"


  [languages.es]
    baseURL = 'https://example.es'
    contentDir = 'content/spanish'
    disabled = false
    languageCode = 'es-419'
    languageDirection = 'ltr'
    languageName = 'Español'
    title = 'En Español'
    weight = 2
    subtitle = "Programadora y Analista de Datos, apasionada por resolver problemas complejos a través del poder de los datos"
    owner = ""
    keywords = "Analisis de Datos, ciencia de datos, visualizacion de datos, Machine Learning, Python, SQL, Portafolio"
    copyright = ""
    menuMore = "Mostrar Más"
    readMore = "Leer Más"
    readOtherPosts = "Leer otros posts"
    newerPosts = "Post más recientes"
    olderPosts = "Post antigüos"
    missingContentMessage = "Página no encontrada..."
    missingBackButtonLabel = "Volver a la página de inicio"
    minuteReadingTime = "min "
    words = "palabras"

    [languages.es.params.logo]
      logoText = "Sandra Ramos"
      logoHomeLink = "./"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Acerca de Mi"
        url = "/acerca"
      [[languages.es.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.es.menu.main]]
        identifier = "projects"
        name = "Proyectos"
        url = "/projects"
      [[languages.es.menu.main]]
        identifier = "resume"
        name = "CV"
        url = "https://cv-data-analytics.vercel.app/"

